numero1 = input("Digite o primeiro número: ")
numero2 = input("Digite o segundo número: ")
soma = float(numero1) + float(numero2)
print(f"A soma dos números é: {soma}")
produto = float(numero1) * float(numero2)
print(f"O produto dos números é: {produto}")